/* TestsGuitar.c generated by valac 0.18.1, the Vala compiler
 * generated from TestsGuitar.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gdk/gdk.h>
#include <gtkmusic.h>
#include <stdio.h>
#include <float.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <gee.h>

#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _gtk_music_guitar_string_unref0(var) ((var == NULL) ? NULL : (var = (gtk_music_guitar_string_unref (var), NULL)))



void note_pressed_callback (GtkWidget* widget, GdkEventButton* event, GtkMusicGuitarPosition* pos);
gint _vala_main (gchar** args, int args_length1);
static void _note_pressed_callback_gtk_music_guitar_note_pressed (GtkMusicGuitar* _sender, GtkWidget* widget, GdkEventButton* event, GtkMusicGuitarPosition* pos, gpointer self);
static void _gtk_main_quit_gtk_widget_destroy (GtkWidget* _sender, gpointer self);


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


void note_pressed_callback (GtkWidget* widget, GdkEventButton* event, GtkMusicGuitarPosition* pos) {
	GtkWidget* _tmp0_;
	GtkMusicGuitar* _tmp1_;
	GtkMusicGuitar* guitar;
	FILE* _tmp2_;
	GtkMusicGuitar* _tmp3_;
	GtkMusicGuitarPosition* _tmp4_;
	gchar* _tmp5_ = NULL;
	gchar* _tmp6_;
	FILE* _tmp7_;
	GdkEventButton _tmp8_;
	guint _tmp9_;
	g_return_if_fail (widget != NULL);
	g_return_if_fail (event != NULL);
	g_return_if_fail (pos != NULL);
	_tmp0_ = widget;
	_tmp1_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp0_, GTK_MUSIC_TYPE_GUITAR) ? ((GtkMusicGuitar*) _tmp0_) : NULL);
	guitar = _tmp1_;
	_tmp2_ = stdout;
	_tmp3_ = guitar;
	_tmp4_ = pos;
	_tmp5_ = gtk_music_guitar_position_to_note (_tmp3_, _tmp4_);
	_tmp6_ = _tmp5_;
	fprintf (_tmp2_, "You clicked a %s!\n", _tmp6_);
	_g_free0 (_tmp6_);
	_tmp7_ = stdout;
	fflush (_tmp7_);
	_tmp8_ = *event;
	_tmp9_ = _tmp8_.button;
	if (_tmp9_ == ((guint) 1)) {
		GtkMusicGuitar* _tmp10_;
		GtkMusicGuitarPosition* _tmp11_;
		gushort _tmp12_;
		GtkMusicGuitarPosition* _tmp13_;
		gushort _tmp14_;
		gfloat* _tmp15_ = NULL;
		gfloat* _tmp16_;
		gint _tmp16__length1;
		_tmp10_ = guitar;
		_tmp11_ = pos;
		_tmp12_ = _tmp11_->stringIndex;
		_tmp13_ = pos;
		_tmp14_ = _tmp13_->fretIndex;
		_tmp15_ = g_new0 (gfloat, 4);
		_tmp15_[0] = 0.0f;
		_tmp15_[1] = 0.0f;
		_tmp15_[2] = 0.0f;
		_tmp15_[3] = 1.0f;
		_tmp16_ = _tmp15_;
		_tmp16__length1 = 4;
		gtk_music_guitar_mark_position (_tmp10_, _tmp12_, _tmp14_, _tmp16_, 4);
		_tmp16_ = (g_free (_tmp16_), NULL);
	} else {
		GtkMusicGuitar* _tmp17_;
		GtkMusicGuitarPosition* _tmp18_;
		gushort _tmp19_;
		GtkMusicGuitarPosition* _tmp20_;
		gushort _tmp21_;
		_tmp17_ = guitar;
		_tmp18_ = pos;
		_tmp19_ = _tmp18_->stringIndex;
		_tmp20_ = pos;
		_tmp21_ = _tmp20_->fretIndex;
		gtk_music_guitar_unmark_position (_tmp17_, _tmp19_, _tmp21_);
	}
	_g_object_unref0 (guitar);
}


static void _note_pressed_callback_gtk_music_guitar_note_pressed (GtkMusicGuitar* _sender, GtkWidget* widget, GdkEventButton* event, GtkMusicGuitarPosition* pos, gpointer self) {
	note_pressed_callback (widget, event, pos);
}


static void _gtk_main_quit_gtk_widget_destroy (GtkWidget* _sender, gpointer self) {
	gtk_main_quit ();
}


gint _vala_main (gchar** args, int args_length1) {
	gint result = 0;
	GtkWindow* _tmp0_;
	GtkWindow* window;
	GtkMusicGuitar* _tmp1_;
	GtkMusicGuitar* guitar;
	GeeArrayList* _tmp2_;
	gpointer _tmp3_ = NULL;
	GtkMusicGuitarString* _tmp4_;
	GeeArrayList* _tmp5_;
	gpointer _tmp6_ = NULL;
	GtkMusicGuitarString* _tmp7_;
	gfloat* _tmp8_ = NULL;
	gfloat* _tmp9_;
	gint _tmp9__length1;
	gfloat* _tmp10_ = NULL;
	gfloat* _tmp11_;
	gint _tmp11__length1;
	gfloat* _tmp12_ = NULL;
	gfloat* _tmp13_;
	gint _tmp13__length1;
	gfloat* _tmp14_ = NULL;
	gfloat* _tmp15_;
	gint _tmp15__length1;
	gfloat* _tmp16_ = NULL;
	gfloat* _tmp17_;
	gint _tmp17__length1;
	gfloat* _tmp18_ = NULL;
	gfloat* _tmp19_;
	gint _tmp19__length1;
	gfloat* _tmp20_ = NULL;
	gfloat* _tmp21_;
	gint _tmp21__length1;
	gtk_init (&args_length1, &args);
	_tmp0_ = (GtkWindow*) gtk_window_new (GTK_WINDOW_TOPLEVEL);
	g_object_ref_sink (_tmp0_);
	window = _tmp0_;
	_tmp1_ = gtk_music_guitar_new ();
	g_object_ref_sink (_tmp1_);
	guitar = _tmp1_;
	g_signal_connect (guitar, "note-pressed", (GCallback) _note_pressed_callback_gtk_music_guitar_note_pressed, NULL);
	_tmp2_ = guitar->guitarStrings;
	_tmp3_ = gee_abstract_list_get ((GeeAbstractList*) _tmp2_, 0);
	_tmp4_ = (GtkMusicGuitarString*) _tmp3_;
	_tmp4_->vibrate = TRUE;
	_gtk_music_guitar_string_unref0 (_tmp4_);
	_tmp5_ = guitar->guitarStrings;
	_tmp6_ = gee_abstract_list_get ((GeeAbstractList*) _tmp5_, 5);
	_tmp7_ = (GtkMusicGuitarString*) _tmp6_;
	_tmp7_->vibrate = TRUE;
	_gtk_music_guitar_string_unref0 (_tmp7_);
	gtk_music_guitar_start_animation (guitar);
	_tmp8_ = g_new0 (gfloat, 4);
	_tmp8_[0] = 0.4f;
	_tmp8_[1] = 0.0f;
	_tmp8_[2] = 0.0f;
	_tmp8_[3] = 1.0f;
	_tmp9_ = _tmp8_;
	_tmp9__length1 = 4;
	gtk_music_guitar_mark_position (guitar, (gushort) 0, (gushort) 0, _tmp9_, 4);
	_tmp9_ = (g_free (_tmp9_), NULL);
	_tmp10_ = g_new0 (gfloat, 4);
	_tmp10_[0] = 0.0f;
	_tmp10_[1] = 0.0f;
	_tmp10_[2] = 0.0f;
	_tmp10_[3] = 1.0f;
	_tmp11_ = _tmp10_;
	_tmp11__length1 = 4;
	gtk_music_guitar_mark_position (guitar, (gushort) 1, (gushort) 1, _tmp11_, 4);
	_tmp11_ = (g_free (_tmp11_), NULL);
	_tmp12_ = g_new0 (gfloat, 4);
	_tmp12_[0] = 0.0f;
	_tmp12_[1] = 0.0f;
	_tmp12_[2] = 0.0f;
	_tmp12_[3] = 1.0f;
	_tmp13_ = _tmp12_;
	_tmp13__length1 = 4;
	gtk_music_guitar_mark_position (guitar, (gushort) 2, (gushort) 1, _tmp13_, 4);
	_tmp13_ = (g_free (_tmp13_), NULL);
	_tmp14_ = g_new0 (gfloat, 4);
	_tmp14_[0] = 0.0f;
	_tmp14_[1] = 0.0f;
	_tmp14_[2] = 0.0f;
	_tmp14_[3] = 1.0f;
	_tmp15_ = _tmp14_;
	_tmp15__length1 = 4;
	gtk_music_guitar_mark_position (guitar, (gushort) 3, (gushort) 0, _tmp15_, 4);
	_tmp15_ = (g_free (_tmp15_), NULL);
	_tmp16_ = g_new0 (gfloat, 4);
	_tmp16_[0] = 0.0f;
	_tmp16_[1] = 0.0f;
	_tmp16_[2] = 0.0f;
	_tmp16_[3] = 1.0f;
	_tmp17_ = _tmp16_;
	_tmp17__length1 = 4;
	gtk_music_guitar_mark_position (guitar, (gushort) 5, (gushort) 3, _tmp17_, 4);
	_tmp17_ = (g_free (_tmp17_), NULL);
	_tmp18_ = g_new0 (gfloat, 4);
	_tmp18_[0] = 0.0f;
	_tmp18_[1] = 0.4f;
	_tmp18_[2] = 0.0f;
	_tmp18_[3] = 1.0f;
	_tmp19_ = _tmp18_;
	_tmp19__length1 = 4;
	gtk_music_guitar_mark_note (guitar, "A3", _tmp19_, 4);
	_tmp19_ = (g_free (_tmp19_), NULL);
	_tmp20_ = g_new0 (gfloat, 4);
	_tmp20_[0] = 0.0f;
	_tmp20_[1] = 0.0f;
	_tmp20_[2] = 0.4f;
	_tmp20_[3] = 0.7f;
	_tmp21_ = _tmp20_;
	_tmp21__length1 = 4;
	gtk_music_guitar_mark_note (guitar, "C", _tmp21_, 4);
	_tmp21_ = (g_free (_tmp21_), NULL);
	gtk_container_add ((GtkContainer*) window, (GtkWidget*) guitar);
	g_signal_connect ((GtkWidget*) window, "destroy", (GCallback) _gtk_main_quit_gtk_widget_destroy, NULL);
	gtk_widget_show_all ((GtkWidget*) window);
	gtk_main ();
	result = 0;
	_g_object_unref0 (guitar);
	_g_object_unref0 (window);
	return result;
}


int main (int argc, char ** argv) {
	g_type_init ();
	return _vala_main (argv, argc);
}



