/* TestsMusicalNotes.c generated by valac 0.18.1, the Vala compiler
 * generated from TestsMusicalNotes.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <gtkmusic.h>

#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))



gint _vala_main (gchar** args, int args_length1);


gint _vala_main (gchar** args, int args_length1) {
	gint result = 0;
	gchar* currNote = NULL;
	gushort currMidi = 0U;
	GError * _inner_error_ = NULL;
	{
		gushort i;
		i = (gushort) 21;
		{
			gboolean _tmp0_;
			_tmp0_ = TRUE;
			while (TRUE) {
				gboolean _tmp1_;
				gushort _tmp3_;
				FILE* _tmp4_;
				gushort _tmp5_;
				FILE* _tmp6_;
				_tmp1_ = _tmp0_;
				if (!_tmp1_) {
					gushort _tmp2_;
					_tmp2_ = i;
					i = _tmp2_ + 1;
				}
				_tmp0_ = FALSE;
				_tmp3_ = i;
				if (!(((gint) _tmp3_) < 34)) {
					break;
				}
				_tmp4_ = stdout;
				_tmp5_ = i;
				fprintf (_tmp4_, "MIDI %u : ", (guint) _tmp5_);
				_tmp6_ = stdout;
				fflush (_tmp6_);
				{
					gushort _tmp7_;
					gchar* _tmp8_ = NULL;
					gchar* _tmp9_;
					FILE* _tmp10_;
					const gchar* _tmp11_;
					_tmp7_ = i;
					_tmp8_ = gtk_music_musical_notes_get_note_from_midi_code (_tmp7_, &_inner_error_);
					_tmp9_ = _tmp8_;
					if (_inner_error_ != NULL) {
						if (_inner_error_->domain == GTK_MUSIC_MUSICAL_NOTE_ERROR) {
							goto __catch0_gtk_music_musical_note_error;
						}
						_g_free0 (currNote);
						g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
						g_clear_error (&_inner_error_);
						return 0;
					}
					_g_free0 (currNote);
					currNote = _tmp9_;
					_tmp10_ = stdout;
					_tmp11_ = currNote;
					fprintf (_tmp10_, "%s", _tmp11_);
				}
				goto __finally0;
				__catch0_gtk_music_musical_note_error:
				{
					GError* m = NULL;
					FILE* _tmp12_;
					FILE* _tmp13_;
					m = _inner_error_;
					_inner_error_ = NULL;
					_tmp12_ = stdout;
					fprintf (_tmp12_, "Invalid MIDI code\n");
					_tmp13_ = stdout;
					fflush (_tmp13_);
					_g_error_free0 (m);
					continue;
				}
				__finally0:
				if (_inner_error_ != NULL) {
					_g_free0 (currNote);
					g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
					g_clear_error (&_inner_error_);
					return 0;
				}
				{
					const gchar* _tmp14_;
					gushort _tmp15_ = 0U;
					gushort _tmp16_;
					FILE* _tmp17_;
					gushort _tmp18_;
					_tmp14_ = currNote;
					_tmp15_ = gtk_music_musical_notes_get_note_as_midi_code (_tmp14_, &_inner_error_);
					_tmp16_ = _tmp15_;
					if (_inner_error_ != NULL) {
						if (_inner_error_->domain == GTK_MUSIC_MUSICAL_NOTE_ERROR) {
							goto __catch1_gtk_music_musical_note_error;
						}
						_g_free0 (currNote);
						g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
						g_clear_error (&_inner_error_);
						return 0;
					}
					currMidi = _tmp16_;
					_tmp17_ = stdout;
					_tmp18_ = currMidi;
					fprintf (_tmp17_, " (%u) \n", (guint) _tmp18_);
				}
				goto __finally1;
				__catch1_gtk_music_musical_note_error:
				{
					GError* m = NULL;
					FILE* _tmp19_;
					FILE* _tmp20_;
					m = _inner_error_;
					_inner_error_ = NULL;
					_tmp19_ = stdout;
					fprintf (_tmp19_, "Invalid note\n");
					_tmp20_ = stdout;
					fflush (_tmp20_);
					_g_error_free0 (m);
				}
				__finally1:
				if (_inner_error_ != NULL) {
					_g_free0 (currNote);
					g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
					g_clear_error (&_inner_error_);
					return 0;
				}
			}
		}
	}
	result = 0;
	_g_free0 (currNote);
	return result;
}


int main (int argc, char ** argv) {
	g_type_init ();
	return _vala_main (argv, argc);
}



